title: Settings
data:
  site_name: 'Dustin LeBlanc'
  social:
    -
      name: Twitter
      url: 'https://twitter.com/DustinLeblanc'
      icon: site/social-icons/twitter.svg
    -
      name: Github
      url: 'http://github.com/dustinleblanc'
      icon: site/social-icons/github.svg
    -
      name: Email
      url: dustin@dustinleblanc.com
      icon: site/social-icons/email.svg
